### ISSUE TITLE
Student Module(P1)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#28]
**Home-> Student-> Manage Students ->Ramu K-> Update Academic Details**.

While i'm updating the student academic details the update button is not working.

![update_error](https://user-images.githubusercontent.com/33898399/33310746-7e7122f4-d3d7-11e7-8918-54a90d60aea2.png)

Thanks & Regards,
Bhadra.

**Comment by pasha05** [comment]
bug fixed, is_status=NULL is an error, am set it as 0.

**Comment by bhadra988** [comment]
but it won't work ( Still update button not working )

**Comment by pasha05** [comment]
Issue is FIXED can you check on apsams next build

**Comment by bhadra988** [comment]
**Not Fixed still existing in samsindia.in and also apsams.in**

**Comment by phanibhushang** [comment]
Issue fixed in samsindia.in, please check.
