### ISSUE TITLE
Student Module(30/11/2017)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#40]
**Home-> Student-> Manage Students ->Ramu K ->Add Guardian Details : Ramu K**

While adding the guardian details, here also mobile and phone number accepts 2 digits. Could you please check all the mobile and phone number text boxes once.

![guardian_error](https://user-images.githubusercontent.com/33898399/33415378-f7f3a088-d54a-11e7-953c-eec78f75831e.png)

Thanks & regards,
Bhadra.

**Comment by pasha05** [comment]
FIXED [PASHA]

**Comment by bhadra988** [comment]
Partially fixed as it is having a problem with the copy the text from some where along with space followed by number, it is accepting as correct. But actually it should throw error message. Please refer below screen shots.
![phone and mobile_error](https://user-images.githubusercontent.com/33898399/33882891-96b65704-deee-11e7-83cb-775073a4f310.png)

**Comment by bhadra988** [comment]
In this mobile number text box working fine, but phone number text box allows only 10 digits, also it shows an error message maximum 15 digits. It not accepting more than 10 digits

![phone_error_gardian](https://user-images.githubusercontent.com/33898399/34434023-219554a0-ec38-11e7-89e6-4d373f0d328c.png)

**Comment by bhadra988** [comment]
working fine
