### ISSUE TITLE
Employee Module:Update button not working (Basic info,Personal info of an employee)

### ISSUE THREAD

**Issue by Shiva578** [srinikoganti/sams#98]
In employee module while edit employee icon  whose employee  not assigning department click on **personal info** tab click on **update** button it shows same page in editable mode again we click on **cancel button** it is redirecting **employee basic info** click on **personal info** tab  of an employee it shows updated data of an employee like below.(**This issue is same for basic info of an employee**)
**Navigation**:Home/ Employee/ Manage Employees/ KOTHAPALLI MAHESH Update Other Details
**Result**:
![emp_personal_update](https://user-images.githubusercontent.com/33898412/33988878-ca6ed8ec-e0eb-11e7-8a33-4a97452c8419.png)

**Comment by pasha05** [comment]
fixed

**Comment by Shiva578** [comment]
not yet fixed and also while editing basic info by default email id getting null value.

**Comment by pasha05** [comment]
It is working fine in 
http://samsindia.in/web/index.php?r=employee%2Femp-master%2Fupdate&empid=7654&tab=otherinfo

**Comment by Shiva578** [comment]
In **Employee Basic info** not yet working please select an employee whose not having department.by default email id text box getting null value it is not going to be updated.please refer(Employee Id:7584)

![emp_basic_update](https://user-images.githubusercontent.com/33898412/34204143-a9c7fb3e-e5a3-11e7-97c3-4a3c2fa8f5b3.png)

**Comment by Shiva578** [comment]
Employee module basic info,while clicking on update button whenever employee email already existing, email Id getting error like below and also values are **not updated** while clicking on **update button** as well as **govt employee id** we entered in the **text box** not shown while updating,no option to enter **Birth place** **but it shown in view with empty value**.
![emp_email](https://user-images.githubusercontent.com/33898412/34348051-e4053314-ea2d-11e7-98a7-2eb21c8946ab.png)

**Comment by Shiva578** [comment]
Govt employee id we are giving following number 6464646546 (should allow 6figit numeric value)it throws an SQL Exception(It is related to #166 )
![image](https://user-images.githubusercontent.com/33898412/34639774-5207a9d2-f30c-11e7-91cc-5b63c8b75b8a.png)

**Comment by Shiva578** [comment]
in employee module **basic info** while clicking on **edit button** **email id getting null value**,if employee not having any **email address** it displays default value as **null**.

**Comment by Shiva578** [comment]
not yet fixed,while click on edit basic info and click on update button, it is in editable mode it is not going to update anymore.
![image](https://user-images.githubusercontent.com/33898412/34705587-6b30ff0e-f527-11e7-8869-7214dba43ddd.png)

**Comment by Shiva578** [comment]
working fine
