### ISSUE TITLE
Student module in Admin login(Pdf error)

### ISSUE THREAD

**Issue by bhadra988** [srinikoganti/sams#99]
**Home ->Student ->Manage Students**
In admin login I'm clicking on pdf and excel buttons it generates the server crash.

![admin_pdf_excel_error](https://user-images.githubusercontent.com/33898399/33990172-e5e222c2-e07e-11e7-9bb2-622eff95135b.png)

![admin_pdf_error1](https://user-images.githubusercontent.com/33898399/33990171-e5af631e-e07e-11e7-9bfc-3b99dc58cc7c.png)

**Comment by pasha05** [comment]
Fixed

**Comment by bhadra988** [comment]
bug not fixed 

![admin_pdf_error1](https://user-images.githubusercontent.com/33898399/34193800-97fb60b8-e54d-11e7-9cbb-9a5cc46e6840.png)
